import { PrismaClient } from "@prisma/client"

const prisma = new PrismaClient()

const CHEESE_IMAGES = [
  {
    provider: "local",
    key: "cheese-1",
    url: "/images/products/1.png",
    alt: "Kaas",
  },
  {
    provider: "local",
    key: "cheese-2",
    url: "/images/products/2.png",
    alt: "Kaas",
  },
  {
    provider: "local",
    key: "cheese-3",
    url: "/images/products/3.png",
    alt: "Kaas",
  },
  {
    provider: "local",
    key: "cheese-4",
    url: "/images/products/4.png",
    alt: "Kaas",
  },
  {
    provider: "local",
    key: "cheese-5",
    url: "/images/products/5.png",
    alt: "Kaas",
  },
  {
    provider: "local",
    key: "cheese-6",
    url: "/images/products/6.png",
    alt: "Kaas",
  },
  {
    provider: "local",
    key: "cheese-7",
    url: "/images/products/7.png",
    alt: "Kaas",
  },
  {
    provider: "local",
    key: "cheese-8",
    url: "/images/products/8.png",
    alt: "Kaas",
  },
  {
    provider: "local",
    key: "cheese-9",
    url: "/images/products/9.png",
    alt: "Kaas",
  },
  {
    provider: "local",
    key: "cheese-11",
    url: "/images/products/11.png",
    alt: "Kaas",
  },
  {
    provider: "local",
    key: "cheese-14",
    url: "/images/products/14.png",
    alt: "Kaas",
  },
  {
    provider: "local",
    key: "cheese-16",
    url: "/images/products/16.png",
    alt: "Kaas",
  },
  {
    provider: "local",
    key: "cheese-17",
    url: "/images/products/17.png",
    alt: "Kaas",
  },
  {
    provider: "local",
    key: "cheese-19",
    url: "/images/products/19.png",
    alt: "Kaas",
  },
  {
    provider: "local",
    key: "cheese-22",
    url: "/images/products/22.png",
    alt: "Kaas",
  },
  {
    provider: "local",
    key: "cheese-23",
    url: "/images/products/23.png",
    alt: "Kaas",
  },
  {
    provider: "local",
    key: "cheese-27",
    url: "/images/products/27.png",
    alt: "Kaas",
  },
]

const CHEESE_PRODUCTS = [
  {
    sku: "CB-CLASSIC",
    name: "Cambozola Classic",
    description: "Duitse blauwader roomkaas met zachte textuur",
    country: "DE",
    floraType: "witflora",
    packagingType: "wiel",
    milkType: "koe",
    ripeningMonths: 2,
    tags: "romig,zacht,blauwader",
    pricePerKg: 24.50,
    unit: "kg",
  },
  {
    sku: "BRIE-FDP-3KG",
    name: "Brie Fleur de Pré 60+",
    description: "Franse brie met bloemige smaak, 3kg wiel",
    country: "FR",
    floraType: "witflora",
    packagingType: "wiel",
    milkType: "koe",
    ripeningMonths: 1,
    tags: "brie,romig,français",
    pricePerKg: 19.00,
    unit: "kg",
  },
  {
    sku: "BRIQUE-1KG",
    name: "Brique Neutre 60+",
    description: "Franse brique kaas, 1kg stuk",
    country: "FR",
    floraType: "witflora",
    packagingType: "stuk",
    milkType: "koe",
    ripeningMonths: 1,
    tags: "zacht,romig",
    pricePerKg: 17.50,
    unit: "kg",
  },
  {
    sku: "MOZZ-ZUGER-1KG",
    name: "Mozzarella Züger",
    description: "Zwitserse mozzarella, 1kg",
    country: "CH",
    floraType: "witflora",
    packagingType: "stuk",
    milkType: "koe",
    ripeningMonths: 0,
    tags: "vers,mild",
    pricePerKg: 12.00,
    unit: "kg",
  },
  {
    sku: "CAM-ALPH-200G",
    name: "Camembert Alphenhain (bak)",
    description: "Duitse camembert in houten bak, 200g",
    country: "DE",
    floraType: "witflora",
    packagingType: "stuk",
    milkType: "koe",
    ripeningMonths: 1,
    tags: "camembert,romig",
    pricePerKg: 28.00,
    unit: "piece",
  },
  {
    sku: "BRIE-MEAUX-3KG",
    name: "Brie de Meaux",
    description: "Authentieke Franse brie AOC, 3kg wiel",
    country: "FR",
    floraType: "witflora",
    packagingType: "wiel",
    milkType: "koe",
    ripeningMonths: 2,
    tags: "aoc,authentiek,brie",
    pricePerKg: 26.00,
    unit: "kg",
  },
  {
    sku: "DELICE-BOURG",
    name: "Délice de Bourgogne",
    description: "Triple crème kaas uit Bourgogne, 1.8kg",
    country: "FR",
    floraType: "witflora",
    packagingType: "wiel",
    milkType: "koe",
    ripeningMonths: 1,
    tags: "triple-crème,luxe,romig",
    pricePerKg: 32.00,
    unit: "kg",
  },
  {
    sku: "GEIT-VERS-1KG",
    name: "Verse Geitenkaas Alphenaer",
    description: "Nederlandse verse geitenkaas, 1kg",
    country: "NL",
    floraType: "witflora",
    packagingType: "stuk",
    milkType: "geit",
    ripeningMonths: 0,
    tags: "geit,vers,mild",
    pricePerKg: 18.00,
    unit: "kg",
  },
  {
    sku: "GEIT-GERIJPT-1KG",
    name: "Gerijpte Geitenkaas Alphenaer",
    description: "Nederlandse gerijpte geitenkaas, 1kg",
    country: "NL",
    floraType: "witflora",
    packagingType: "stuk",
    milkType: "geit",
    ripeningMonths: 3,
    tags: "geit,gerijpt,karakter",
    pricePerKg: 22.00,
    unit: "kg",
  },
  {
    sku: "GEIT-BRIE-1.5KG",
    name: "Geitenbrie Alphenaer Naturel",
    description: "Nederlandse geitenbrie, 1.5kg wiel",
    country: "NL",
    floraType: "witflora",
    packagingType: "wiel",
    milkType: "geit",
    ripeningMonths: 2,
    tags: "geit,brie,romig",
    pricePerKg: 24.00,
    unit: "kg",
  },
  {
    sku: "LA-TUR",
    name: "La Tur",
    description: "Italiaanse triple melk kaas (koe, geit, schaap)",
    country: "IT",
    floraType: "witflora",
    packagingType: "stuk",
    milkType: "koe",
    ripeningMonths: 1,
    tags: "luxe,romig,italië",
    pricePerKg: 38.00,
    unit: "piece",
  },
  {
    sku: "MOZZ-GALBANI",
    name: "Mozzarella Galbani",
    description: "Klassieke Italiaanse mozzarella",
    country: "IT",
    floraType: "witflora",
    packagingType: "stuk",
    milkType: "koe",
    ripeningMonths: 0,
    tags: "mozzarella,vers,italië",
    pricePerKg: 9.50,
    unit: "kg",
  },
  {
    sku: "MASC-500G",
    name: "Mascarpone Castelli 500g",
    description: "Italiaanse mascarpone, 500g",
    country: "IT",
    floraType: "witflora",
    packagingType: "smeerkaas",
    milkType: "koe",
    ripeningMonths: 0,
    tags: "mascarpone,dessert,romig",
    pricePerKg: 16.00,
    unit: "piece",
  },
  {
    sku: "MASC-2KG",
    name: "Mascarpone Castelli 2kg",
    description: "Italiaanse mascarpone, 2kg",
    country: "IT",
    floraType: "witflora",
    packagingType: "smeerkaas",
    milkType: "koe",
    ripeningMonths: 0,
    tags: "mascarpone,dessert,romig",
    pricePerKg: 14.00,
    unit: "kg",
  },
  {
    sku: "CROTTIN-60G",
    name: "Crottin Germain",
    description: "Franse geitenkaa crottin, 60g",
    country: "FR",
    floraType: "witflora",
    packagingType: "stuk",
    milkType: "geit",
    ripeningMonths: 1,
    tags: "geit,klein,authentiek",
    pricePerKg: 42.00,
    unit: "piece",
  },
  {
    sku: "TOMME-CHEVRE-1.1KG",
    name: "Tomme Chèvre Fouzon",
    description: "Franse geitenkaas tomme, 1.1kg",
    country: "FR",
    floraType: "witflora",
    packagingType: "wiel",
    milkType: "geit",
    ripeningMonths: 2,
    tags: "geit,tomme,français",
    pricePerKg: 26.00,
    unit: "kg",
  },
  {
    sku: "ST-MAURE",
    name: "St. Maure",
    description: "Franse geitenkaas in kenmerkende vorm met stro",
    country: "FR",
    floraType: "witflora",
    packagingType: "stuk",
    milkType: "geit",
    ripeningMonths: 2,
    tags: "geit,authentiek,français",
    pricePerKg: 28.00,
    unit: "piece",
  },
  {
    sku: "CHAOURCE-250G",
    name: "Chaource Germain",
    description: "Franse Chaource kaas, 250g",
    country: "FR",
    floraType: "witflora",
    packagingType: "stuk",
    milkType: "koe",
    ripeningMonths: 2,
    tags: "romig,zacht,français",
    pricePerKg: 34.00,
    unit: "piece",
  },
  {
    sku: "SKEAPSROND",
    name: "Skeapsrond",
    description: "Nederlandse schapenkaas wiel",
    country: "NL",
    floraType: "witflora",
    packagingType: "wiel",
    milkType: "schaap",
    ripeningMonths: 2,
    tags: "schaap,nederlands,bijzonder",
    pricePerKg: 29.00,
    unit: "kg",
  },
  {
    sku: "BURRATA-100G",
    name: "Burrata",
    description: "Italiaanse burrata, 100g",
    country: "IT",
    floraType: "witflora",
    packagingType: "stuk",
    milkType: "koe",
    ripeningMonths: 0,
    tags: "burrata,luxe,vers",
    pricePerKg: 45.00,
    unit: "piece",
  },
  {
    sku: "TOMA-PIETRA",
    name: "Toma Pietra",
    description: "Italiaanse Toma kaas",
    country: "IT",
    floraType: "witflora",
    packagingType: "wiel",
    milkType: "koe",
    ripeningMonths: 3,
    tags: "italië,bergkaas",
    pricePerKg: 22.00,
    unit: "kg",
  },
  {
    sku: "WITTE-KONING",
    name: "Witte van Koning",
    description: "Nederlandse zachte witte kaas",
    country: "NL",
    floraType: "witflora",
    packagingType: "wiel",
    milkType: "koe",
    ripeningMonths: 1,
    tags: "nederlands,zacht",
    pricePerKg: 16.00,
    unit: "kg",
  },
  {
    sku: "BROMMELS",
    name: "Brommels",
    description: "Nederlandse zachte kaas",
    country: "NL",
    floraType: "witflora",
    packagingType: "wiel",
    milkType: "koe",
    ripeningMonths: 1,
    tags: "nederlands,zacht",
    pricePerKg: 15.00,
    unit: "kg",
  },
  {
    sku: "FETA-DODONI-200G",
    name: "Feta Dodoni",
    description: "Griekse feta kaas, 200g",
    country: "NL",
    floraType: "witflora",
    packagingType: "stuk",
    milkType: "schaap",
    ripeningMonths: 0,
    tags: "feta,grieks,schaap",
    pricePerKg: 18.00,
    unit: "piece",
  },
  {
    sku: "BOER-MEIKAAS",
    name: "Boer Witte Meikaas",
    description: "Nederlandse boeren meikaas",
    country: "NL",
    floraType: "witflora",
    packagingType: "wiel",
    milkType: "koe",
    ripeningMonths: 1,
    tags: "boer,meikaas,ambachtelijk",
    pricePerKg: 20.00,
    unit: "kg",
  },
  {
    sku: "SPUIT-GEIT-500G",
    name: "Spuitzak Geitenkaas",
    description: "Nederlandse geitenkaas in spuitzak, 500g",
    country: "NL",
    floraType: "witflora",
    packagingType: "smeerkaas",
    milkType: "geit",
    ripeningMonths: 0,
    tags: "geit,smeerkaas,vers",
    pricePerKg: 22.00,
    unit: "piece",
  },
  {
    sku: "ROOMKAAS-NAT-1.25KG",
    name: "Roomkaas Naturel",
    description: "Nederlandse roomkaas naturel, 1.25kg",
    country: "NL",
    floraType: "witflora",
    packagingType: "smeerkaas",
    milkType: "koe",
    ripeningMonths: 0,
    tags: "roomkaas,naturel",
    pricePerKg: 8.50,
    unit: "kg",
  },
  {
    sku: "ROOMKAAS-BIES-1.25KG",
    name: "Roomkaas Bieslook",
    description: "Nederlandse roomkaas met bieslook, 1.25kg",
    country: "NL",
    floraType: "witflora",
    packagingType: "smeerkaas",
    milkType: "koe",
    ripeningMonths: 0,
    tags: "roomkaas,bieslook,kruiden",
    pricePerKg: 9.00,
    unit: "kg",
  },
  {
    sku: "FETA-PEKAL-1KG",
    name: "Feta op Pekal 40+",
    description: "Nederlandse feta in pekel, 1kg",
    country: "NL",
    floraType: "witflora",
    packagingType: "stuk",
    milkType: "schaap",
    ripeningMonths: 0,
    tags: "feta,pekel,schaap",
    pricePerKg: 14.00,
    unit: "kg",
  },
  {
    sku: "MOZZ-BUFALA-125G",
    name: "Mozzarella Bufala",
    description: "Italiaanse buffel mozzarella, 125g",
    country: "IT",
    floraType: "witflora",
    packagingType: "stuk",
    milkType: "buffel",
    ripeningMonths: 0,
    tags: "buffel,mozzarella,luxe",
    pricePerKg: 55.00,
    unit: "piece",
  },
  {
    sku: "DORUVAEL-PETIT",
    name: "Le Petit Doruvael",
    description: "Franse gewassen korstkaas",
    country: "FR",
    floraType: "roodflora",
    packagingType: "stuk",
    milkType: "koe",
    ripeningMonths: 3,
    tags: "roodflora,français,karakter",
    pricePerKg: 28.00,
    unit: "piece",
  },
  {
    sku: "DORUVAEL-TRUFFEL",
    name: "Doruvael Truffel",
    description: "Franse gewassen korstkaas met truffel",
    country: "FR",
    floraType: "roodflora",
    packagingType: "stuk",
    milkType: "koe",
    ripeningMonths: 3,
    tags: "roodflora,truffel,luxe",
    pricePerKg: 42.00,
    unit: "piece",
  },
  {
    sku: "EPOISSES",
    name: "Epoisses",
    description: "Franse gewassen korstkaas met sterke geur",
    country: "FR",
    floraType: "roodflora",
    packagingType: "wiel",
    milkType: "koe",
    ripeningMonths: 4,
    tags: "roodflora,sterk,aoc",
    pricePerKg: 38.00,
    unit: "kg",
  },
  {
    sku: "MORBIER",
    name: "Morbier",
    description: "Franse halfharde kaas met aslaag",
    country: "FR",
    floraType: "roodflora",
    packagingType: "wiel",
    milkType: "koe",
    ripeningMonths: 6,
    tags: "roodflora,aslaag,français",
    pricePerKg: 24.00,
    unit: "kg",
  },
  {
    sku: "MUNSTER",
    name: "Munster",
    description: "Pittige kaas uit de Elzas",
    country: "FR",
    floraType: "roodflora",
    packagingType: "wiel",
    milkType: "koe",
    ripeningMonths: 3,
    tags: "roodflora,pittig,elzas",
    pricePerKg: 22.00,
    unit: "kg",
  },
  {
    sku: "COMTE",
    name: "Comté",
    description: "Franse bergkaas met nootachtige smaak",
    country: "FR",
    floraType: "hard",
    packagingType: "wiel",
    milkType: "koe",
    ripeningMonths: 12,
    tags: "hard,nootachtig,aoc",
    pricePerKg: 26.00,
    unit: "kg",
  },
  {
    sku: "EMMENTALER-AOC",
    name: "Emmentaler AOC",
    description: "Zwitserse kaas met grote gaten",
    country: "CH",
    floraType: "hard",
    packagingType: "wiel",
    milkType: "koe",
    ripeningMonths: 10,
    tags: "hard,gaten,zwitsers",
    pricePerKg: 22.00,
    unit: "kg",
  },
  {
    sku: "ALTA-BADIA",
    name: "Alta Badia",
    description: "Italiaanse bergkaas met pittig aroma",
    country: "IT",
    floraType: "hard",
    packagingType: "wiel",
    milkType: "koe",
    ripeningMonths: 14,
    tags: "hard,bergkaas,pittig",
    pricePerKg: 28.00,
    unit: "kg",
  },
  {
    sku: "MANCHEGO",
    name: "Manchego",
    description: "Spaanse schapenkaas",
    country: "ES",
    floraType: "hard",
    packagingType: "wiel",
    milkType: "schaap",
    ripeningMonths: 12,
    tags: "hard,schaap,spaans",
    pricePerKg: 32.00,
    unit: "kg",
  },
  {
    sku: "PARMIGIANO",
    name: "Parmigiano Reggiano",
    description: "Italiaanse harde kaas DOP",
    country: "IT",
    floraType: "hard",
    packagingType: "stuk",
    milkType: "koe",
    ripeningMonths: 24,
    tags: "hard,parmigiano,dop",
    pricePerKg: 36.00,
    unit: "kg",
  },
  {
    sku: "PECORINO-ROMANO",
    name: "Pecorino Romano",
    description: "Italiaanse schapenkaas DOP",
    country: "IT",
    floraType: "hard",
    packagingType: "stuk",
    milkType: "schaap",
    ripeningMonths: 8,
    tags: "hard,schaap,dop",
    pricePerKg: 28.00,
    unit: "kg",
  },
  {
    sku: "GRUYERE",
    name: "Gruyère",
    description: "Zwitserse bergkaas AOC",
    country: "CH",
    floraType: "hard",
    packagingType: "wiel",
    milkType: "koe",
    ripeningMonths: 12,
    tags: "hard,gruyère,aoc",
    pricePerKg: 30.00,
    unit: "kg",
  },
  {
    sku: "ROQUEFORT",
    name: "Roquefort",
    description: "Franse schapenkaas met pittige blauwaders",
    country: "FR",
    floraType: "blauwader",
    packagingType: "wiel",
    milkType: "schaap",
    ripeningMonths: 4,
    tags: "blauwader,schaap,aoc",
    pricePerKg: 34.00,
    unit: "kg",
  },
  {
    sku: "SHROPSHIRE-BLUE",
    name: "Shropshire Blue",
    description: "Engelse blauwader met romige textuur",
    country: "NL",
    floraType: "blauwader",
    packagingType: "wiel",
    milkType: "koe",
    ripeningMonths: 10,
    tags: "blauwader,romig,engels",
    pricePerKg: 26.00,
    unit: "kg",
  },
  {
    sku: "BLEU-AUVERGNE",
    name: "Bleu d'Auvergne",
    description: "Franse blauwader met romige textuur",
    country: "FR",
    floraType: "blauwader",
    packagingType: "wiel",
    milkType: "koe",
    ripeningMonths: 4,
    tags: "blauwader,romig,français",
    pricePerKg: 22.00,
    unit: "kg",
  },
  {
    sku: "GORGONZOLA",
    name: "Gorgonzola",
    description: "Italiaanse blauwader DOP",
    country: "IT",
    floraType: "blauwader",
    packagingType: "wiel",
    milkType: "koe",
    ripeningMonths: 3,
    tags: "blauwader,italië,dop",
    pricePerKg: 20.00,
    unit: "kg",
  },
  {
    sku: "STILTON",
    name: "Stilton",
    description: "Engelse blauwader",
    country: "NL",
    floraType: "blauwader",
    packagingType: "wiel",
    milkType: "koe",
    ripeningMonths: 12,
    tags: "blauwader,engels,karakter",
    pricePerKg: 28.00,
    unit: "kg",
  },
]

async function main() {
  console.log("🌱 Starting seed...")

  const admin1 = await prisma.user.upsert({
    where: { email: "fried.scholvinck@gmail.com" },
    update: { role: "admin" },
    create: {
      email: "fried.scholvinck@gmail.com",
      name: "Fried Scholvinck",
      role: "admin",
    },
  })
  console.log(`✅ Admin user: ${admin1.email}`)

  const admin2 = await prisma.user.upsert({
    where: { email: "hein@jeroennoekaas.nl" },
    update: { role: "admin" },
    create: {
      email: "hein@jeroennoekaas.nl",
      name: "Hein",
      role: "admin",
    },
  })
  console.log(`✅ Admin user: ${admin2.email}`)

  const client = await prisma.user.upsert({
    where: { email: "fried.scholvinck@proton.me" },
    update: { role: "client" },
    create: {
      email: "fried.scholvinck@proton.me",
      name: "Fried (Client)",
      role: "client",
    },
  })
  console.log(`✅ Client user: ${client.email}`)

  for (const imgData of CHEESE_IMAGES) {
    await prisma.imageAsset.upsert({
      where: { key: imgData.key },
      update: {},
      create: imgData,
    })
  }
  console.log(`✅ Created ${CHEESE_IMAGES.length} cheese images`)

  const images = await prisma.imageAsset.findMany()
  
  for (let i = 0; i < CHEESE_PRODUCTS.length; i++) {
    const product = CHEESE_PRODUCTS[i]
    const image = images[i % images.length]
    
    await prisma.product.upsert({
      where: { sku: product.sku },
      update: {},
      create: {
        ...product,
        slug: product.name.toLowerCase().replace(/[^a-z0-9]+/g, '-'),
        imageId: image.id,
      },
    })
  }
  console.log(`✅ Created ${CHEESE_PRODUCTS.length} cheese products`)

  await prisma.lead.create({
    data: {
      name: "Jan de Vries",
      email: "jan@example.com",
      message: "Geïnteresseerd in samenwerking voor mijn restaurant in Amsterdam.",
      source: "contact-form",
    },
  })
  console.log("✅ Created demo lead")

  console.log("🎉 Seed completed!")
}

main()
  .catch((e) => {
    console.error("❌ Seed failed:", e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })

